---
title: "Depression Draft 1"
author: "Christy Hui"
date: "2024-11-30"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cowplot)
library(caret)
library(ROCR)
library(sjPlot)
library(visdat)
```

```{r}
# read data
depression = read.csv("final_depression_dataset_1.csv")
```

```{r}
# find the dimension of depression
dim(depression)
```

```{r}
# find if there exist duplicates
sum(duplicated(depression))
```

```{r}
vis_miss(depression)
```

```{r}
# find number of NAs for each column
sapply(depression, function(x) {sum(is.na(x))})
```

```{r}
# combine pressure columns into one
helper1 = ifelse(is.na(depression$Academic.Pressure), 0, depression$Academic.Pressure)

helper2 = ifelse(is.na(depression$Work.Pressure), 0, depression$Work.Pressure)

depression$Pressure = helper1 + helper2
```

```{r}
# combine satisfaction into one column
helper3 = ifelse(is.na(depression$Study.Satisfaction), 0, depression$Study.Satisfaction)

helper4 = ifelse(is.na(depression$Job.Satisfaction), 0, depression$Job.Satisfaction)

depression$Satisfaction = helper3 + helper4
```

```{r}
# delete columns with NAs
depression = depression[, -c(7:11)]
sapply(depression, function(x) {sum(is.na(x))})
```

```{r}
# due to a large amount of varied answers for "City" and "Profession," we delete the variables
# we also delete name because we don't care about that variable
unique(depression$City)
unique(depression$Profession)

depression = subset(depression, select = -c(Name, City, Profession))
```

```{r}
# degree has many varied answers as well; however, they can be recoded into three main categories: high school equivalent, bachelors, masters, PhD
unique(depression$Degree)
```

```{r}
# recode degree into three categories
depression$Degree = case_when(depression$Degree == "Class 12" ~ "High School Equivalent",
                              grepl("^[BL]", depression$Degree) ~ "Bachelors Degree",
                              grepl("^[MP]", depression$Degree) ~ "Post-Graduate Degree")

table(depression$Degree)
```

```{r}
# find type of each variable so we can change each type
sapply(depression, function(x) {class(x)})
```

```{r}
# change each categorical into a factor, changing the base/ordering them if needed
depression$Gender = as.factor(depression$Gender)
depression$Working.Professional.or.Student = as.factor(depression$Working.Professional.or.Student)
depression$Sleep.Duration = factor(depression$Sleep.Duration, levels = c("Less than 5 hours", "5-6 hours", "7-8 hours", "More than 8 hours"), ordered = TRUE)
depression$Dietary.Habits = factor(depression$Dietary.Habits, levels = c("Unhealthy", "Moderate", "Healthy"))
depression$Degree = factor(depression$Degree, levels = c("High School Equivalent", "Bachelors Degree", "Post-Graduate Degree"))
depression$Have.you.ever.had.suicidal.thoughts.. = as.factor(depression$Have.you.ever.had.suicidal.thoughts..)
depression$Family.History.of.Mental.Illness = as.factor(depression$Family.History.of.Mental.Illness)
depression$Depression = as.factor(depression$Depression)
```

```{r}
# find if any variables are unbalanced
depressionFactored = select(depression, where(is.factor))
sapply(depressionFactored, table)
```

```{r}
# plot depression count
ggplot(depression, aes(x = Depression)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Depression") +
  ylab("Count") +
  ggtitle("Barplot of Depression") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
```

```{r}
# plot gender
ggplot(depression, aes(x = Gender)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Gender") +
  ylab("Count") +
  ggtitle("Barplot of Gender") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Gender)
prop.table(table(depression$Depression, depression$Gender), margin = 1)
```

```{r}
# plot whether or not person is a working professional or student
ggplot(depression, aes(x = Working.Professional.or.Student)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Occupation") +
  ylab("Count") +
  ggtitle("Barplot of Professional/Student") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Working.Professional.or.Student)
prop.table(table(depression$Depression, depression$Working.Professional.or.Student), margin = 1)
```

```{r}
# plot sleep duration habits
ggplot(depression, aes(x = Sleep.Duration)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Sleep Duration") +
  ylab("Count") +
  ggtitle("Barplot of Sleep Duration") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Sleep.Duration)
prop.table(table(depression$Depression, depression$Sleep.Duration), margin = 1)
```

```{r}
# plot dietary habits
ggplot(depression, aes(x = Dietary.Habits)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Dietary Habits") +
  ylab("Count") +
  ggtitle("Barplot of Dietary Habits") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Dietary.Habits)
prop.table(table(depression$Depression, depression$Dietary.Habits), margin = 1)
```

```{r}
# plot degree count
ggplot(depression, aes(x = Degree)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Degree") +
  ylab("Count") +
  ggtitle("Barplot of Degree") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Degree)
prop.table(table(depression$Depression, depression$Degree), margin = 1)
```

```{r}
# plot degree count
ggplot(depression, aes(x = Have.you.ever.had.suicidal.thoughts..)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Suicidal Thoughts") +
  ylab("Count") +
  ggtitle("Barplot of Suicidal Thoughts") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Have.you.ever.had.suicidal.thoughts..)
prop.table(table(depression$Depression, depression$Have.you.ever.had.suicidal.thoughts..), margin = 1)
```

```{r}
# delete suicidal thoughts variable
depression = subset(depression, select = -c(Have.you.ever.had.suicidal.thoughts..))
```

```{r}
# plot financial stress count
ggplot(depression, aes(x = Financial.Stress)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Financial Stress Score") +
  ylab("Count") +
  ggtitle("Barplot of Financial Stress Score") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Financial.Stress)
prop.table(table(depression$Depression, depression$Financial.Stress), margin = 1)
```

```{r}
# plot family history of mental illness count
ggplot(depression, aes(x = Family.History.of.Mental.Illness)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Mental Illness Family History") +
  ylab("Count") +
  ggtitle("Barplot of Mental Illness Family History") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Family.History.of.Mental.Illness)
prop.table(table(depression$Depression, depression$Family.History.of.Mental.Illness), margin = 1)
```

```{r}
# plot financial stress count
ggplot(depression, aes(x = Pressure)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Pressure Score") +
  ylab("Count") +
  ggtitle("Barplot of Pressure Score") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Pressure)
prop.table(table(depression$Depression, depression$Pressure), margin = 1)
```

```{r}
ggplot(depression, aes(x = Satisfaction)) + 
  geom_bar(aes(fill = Depression)) + 
  xlab("Satisfaction Score") +
  ylab("Count") +
  ggtitle("Barplot of Pressure Score") + 
  geom_text(aes(label = ..count..), stat = "count", vjust = 2)
table(depression$Depression, depression$Satisfaction)
prop.table(table(depression$Depression, depression$Satisfaction), margin = 1)
```

```{r}
# create specific data frames to separate those with and without risk of depression
depressionYes = depression[depression$Depression == "Yes", ]
depressionNo = depression[depression$Depression == "No", ]
```

```{r}
ggplot(depression, aes(x = Age, y = after_stat(density))) +
  geom_histogram(binwidth = 1, fill="#69B3A2", color = "#E9ECEF") +
  geom_density(color = "#FF9933", linewidth = 0.7, adjust = 0.3) + 
  ggtitle("Frequency of Age") +
  ylab("Frequency")
```

```{r}
p1 = ggplot(depressionYes, aes(x = Age, y = after_stat(density))) +
  geom_histogram(binwidth = 1, fill="#69B3A2", color = "#E9ECEF") +
  geom_density(color = "#FF9933", linewidth = 0.7, adjust = 0.3) + 
  ggtitle("Age of Depressed Yes") +
  ylab("Frequency") + 
  ylim(0, 0.10)

p2 = ggplot(depressionNo, aes(x = Age, y = after_stat(density))) +
  geom_histogram(binwidth = 1, fill="#69B3A2", color = "#E9ECEF") +
  geom_density(color = "#FF9933", linewidth = 0.7, adjust = 0.3) + 
  ggtitle("Age of Depressed No") +
  ylab("Frequency") + 
  ylim(0, 0.10)
```

```{r}
cowplot::plot_grid(p1, p2)
```

```{r}
ggplot(depression, aes(x = Work.Study.Hours, y = after_stat(density))) +
  geom_histogram(binwidth = 1, fill="#69B3A2", color = "#E9ECEF") +
  geom_density(color = "#FF9933", linewidth = 0.7, adjust = 1) + 
  ggtitle("Frequency of Work/Study Hours") +
  xlab("Hours Spent Working/Studying") +
  ylab("Frequency")
```

```{r}
p3 = ggplot(depressionYes, aes(x = Work.Study.Hours, y = after_stat(density))) +
  geom_histogram(binwidth = 1, fill="#69B3A2", color = "#E9ECEF") +
  geom_density(color = "#FF9933", linewidth = 0.7, adjust = 1) + 
  ggtitle("Work/Study Hours of Depressed Yes") +
  xlab("Hours Spent Working/Studying") +
  ylab("Frequency") + 
  ylim(0, 0.15)

p4 = ggplot(depressionNo, aes(x = Work.Study.Hours, y = after_stat(density))) +
  geom_histogram(binwidth = 1, fill="#69B3A2", color = "#E9ECEF") +
  geom_density(color = "#FF9933", linewidth = 0.7, adjust = 1) + 
  ggtitle("Work/Study Hours of Depressed No") +
  xlab("Hours Spent Working/Studying") +
  ylab("Frequency") + 
  ylim(0, 0.15)
```

```{r}
cowplot::plot_grid(p3, p4, ncol = 2)
```

```{r}
# create train and test set
set.seed(213)
index = createDataPartition(depression$Depression, p = 0.80, list = FALSE, times = 1)
depression_train = depression[index,]
depression_test = depression[-index,]
```

```{r}
# create model with all predictors (no interaction effects)
depression_glm = glm(Depression ~ ., data = depression_train, family = "binomial")
summary(depression_glm)
```

```{r}
# draw a roc curve for true positive rate and true negative rate to find the optimal cutoff
glm_predictions = predict(depression_glm, newdata = depression_test, type = "response")
prob_predictions = prediction(glm_predictions, depression_test$Depression)
roc_curve = performance(prob_predictions, "tpr", "fpr")
plot(roc_curve, colorize = TRUE, main = "Model 1 (Only Main Effects) ROC Curve - TPR/FPR")
abline(0, 1)
```

```{r}
# auc value
unlist(slot(performance(prob_predictions, "auc"), "y.values"))
```

```{r}
acc = performance(prob_predictions, "acc")
plot(acc, main = "Model 1 (Only Main Effects) ROC Curve - Accuracy")
abline(0, 1)
```

```{r}
glm_predictions2 = predict(depression_glm, newdata = depression_test)
glm_predictions2 = ifelse(glm_predictions2 > 0.35, "Yes", "No")
glm_predictions2 = as.factor(glm_predictions2)
confusionMatrix(glm_predictions2, depression_test$Depression)
```

```{r}
# create models for interaction effects of each categorical variable and see if there are any significant
# summary(glm(Depression ~ Gender*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Working.Professional.or.Student*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Sleep.Duration*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Dietary.Habits*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Degree*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Work.Study.Hours*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Financial.Stress*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Family.History.of.Mental.Illness*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Pressure*., data = depression_train, family = "binomial"))
```

```{r}
# summary(glm(Depression ~ Satisfaction*., data = depression_train, family = "binomial"))
```

None of the interaction effects were meaningfully significant; we will not be adding interaction effects to our model.

```{r}
# create a table to easily see top important predictors and their odds for the first model
vI = cbind(varImp(depression_glm), Odds = exp(summary(depression_glm)$coefficients[-1, 1]), PValue = summary(depression_glm)$coefficients[-1, 4])
vI = vI[order(-vI$Overall), , drop = FALSE]
vI
```

```{r}
depression_glm2 = glm(Depression ~ Age + Pressure + Satisfaction + Work.Study.Hours + Financial.Stress, data = depression_train, family = "binomial")
summary(depression_glm2)
```

```{r}
# draw a roc curve for true positive rate and true negative rate to find the optimal cutoff
glm_predictions3 = predict(depression_glm2, newdata = depression_test, type = "response")
prob_predictions2 = prediction(glm_predictions3, depression_test$Depression)
roc_curve2 = performance(prob_predictions2, "tpr", "fpr")
plot(roc_curve2, colorize = TRUE, main = "Model 13 (Only Main Effects) ROC Curve - TPR/FPR")
abline(0, 1)
```

```{r}
# auc value
unlist(slot(performance(prob_predictions2, "auc"), "y.values"))
```

```{r}
acc2 = performance(prob_predictions2, "acc")
plot(acc2, main = "Model 13 (Only Main Effects) ROC Curve - Accuracy")
abline(0, 1)
```

```{r}
glm_predictions4 = predict(depression_glm2, newdata = depression_test)
glm_predictions4 = ifelse(glm_predictions4 > 0.35, "Yes", "No")
glm_predictions4 = as.factor(glm_predictions4)
confusionMatrix(glm_predictions4, depression_test$Depression)
```

```{r}
# create a table to easily see top important predictors and their odds for the second model
vI2 = cbind(varImp(depression_glm2), Odds = exp(summary(depression_glm2)$coefficients[-1, 1]), PValue = summary(depression_glm2)$coefficients[-1, 4])
vI2 = vI2[order(-vI2$Overall), , drop = FALSE]
vI2
```

```{r}
paste("First Model Residual Deviance: ", depression_glm$deviance)
paste("Second Model Residual Deviance: ", depression_glm2$deviance)
```

```{r}
train_control = trainControl(method = "repeatedcv", number = 10, repeats = 3, classProbs = TRUE)
depression_cvglm = train(Depression ~ .,
                         data = depression_train,
                         method = "glm",
                         family = binomial,
                         trControl = train_control)
```

```{r}
depression_cvglm$results
```

```{r}
cvglm_predictions = predict(depression_cvglm, depression_test)
confusionMatrix(cvglm_predictions, depression_test$Depression)
```

```{r}
varImp(depression_cvglm)
```

```{r}
train_control2 = trainControl(method = "repeatedcv", number = 10, repeats = 3, classProbs = TRUE)
depression_cvglm2 = train(Depression ~ Age + Pressure + Satisfaction + Work.Study.Hours + Financial.Stress,
                         data = depression_train,
                         method = "glm",
                         family = binomial,
                         trControl = train_control2)
```

```{r}
depression_cvglm2$results
```

```{r}
cvglm_predictions2 = predict(depression_cvglm2, depression_test)
confusionMatrix(cvglm_predictions2, depression_test$Depression)
```

```{r}
varImp(depression_cvglm2)
```

```{r}
plot_model(depression_glm, title = "Depression - First Model")
```

```{r}
plot_model(depression_glm2, title = "Depression - Second Model")
```

$$
\text{logit}(p) = 1.538 - 0.235 * Age + 0.977 * Pressure - 0.737 * Satisfaction + 0.218 * Work.Study.Hours + 0.590 * Financial.Stress
$$

$$
\text{where logit}(p) = ln(\frac{p}{1-p}) = \beta_0+\beta_1X_1 + \beta_2X_2 + ... + \beta_nX_n + 
$$

